# Generated by Django 5.2.5 on 2026-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('dept', models.CharField(max_length=33)),
                ('rollno', models.IntegerField()),
            ],
        ),
    ]
